title: Zachary Nikkel  Software Developer # your name (or website title) here
logo: "/images/IMG_7130.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello and welcome to my portfolio! I am a Software Develoment Graduate from Helena College UM with a passion for coding challenges and exploring new technologies.
  <br><br>
  Outside of the software world, I have several hobbies that keep me balanced. Whether I'm writing code or exploring the wonders of nature, I always bring my curiosity and creativity along.
  <br><br>
  <a href="https://www.linkedin.com/in/zachary-nikkel-44a765148/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
